name: Node CI

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        npm ci
        npm run copy:others:sample
        npm run copy:others:src
        npm run build:sample --if-present
      env:
        CI: true
  deploy:
    needs: build
    
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to GitHub Pages
        uses: maxheld83/ghpages@v0.2.1
        env:
          BUILD_DIR: static
          GH_PAT: ${{ secrets.GH_PAT }}
